colors:
  primary:
    foreground: '#575279'
    background: '#faf4ed'
    dim_foreground: '#797593'
    bright_foreground: '#575279'
  cursor:
    text: '#575279'
    cursor: '#cecacd'
  vi_mode_cursor:
    text: '#575279'
    cursor: '#cecacd'
  search:
    matches:
      foreground: '#797593'
      background: '#f2e9e1'
    focused_match:
      foreground: '#faf4ed'
      background: '#d7827e'
  hints:
    start:
      foreground: '#797593'
      background: '#fffaf3'
    end:
      foreground: '#9893a5'
      background: '#fffaf3'
  line_indicator:
    foreground: None
    background: None
  footer_bar:
    foreground: '#575279'
    background: '#fffaf3'
  selection:
    text: '#575279'
    background: '#dfdad9'
  normal:
    black: '#f2e9e1'
    red: '#b4637a'
    green: '#286983'
    yellow: '#ea9d34'
    blue: '#56949f'
    magenta: '#907aa9'
    cyan: '#d7827e'
    white: '#575279'
  bright:
    black: '#9893a5'
    red: '#b4637a'
    green: '#286983'
    yellow: '#ea9d34'
    blue: '#56949f'
    magenta: '#907aa9'
    cyan: '#d7827e'
    white: '#575279'
  dim:
    black: '#9893a5'
    red: '#b4637a'
    green: '#286983'
    yellow: '#ea9d34'
    blue: '#56949f'
    magenta: '#907aa9'
    cyan: '#d7827e'
    white: '#575279'
