palette = "catppuccin_mocha"

format = """
[](fg:surface0)\
$shell[ ](bg:surface0)\
$directory[ ](bg:surface0)\
$username[ ](bg:surface0)\
$status\
[](fg:surface0) \
"""
right_format = """
[](fg:surface0)\
$time\
[](fg:surface0)\
"""

[fill]
symbol = ' '

[username]
style_root = 'fg:red bg:surface0'
style_user = 'fg:red bg:surface0' 
format = '[ usr $user ]($style)'
disabled = false

[directory]
style = "fg:yellow bg:surface0"
format = "[ dir $path ]($style)"
truncation_length = 2
truncation_symbol = '.../'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[status]
style = 'fg:maroon bg:surface0'
recognize_signal_code = false
format = '[ status $status ]($style)'
map_symbol = true
disabled = false

[shell]
style = 'fg:blue bg:surface0'
format = '[ shell $indicator ]($style)'
disabled = false

[time]
disabled = false
style = 'fg:pink bg:surface0'
format = '[ time $time ]($style)'
time_format = '%F | %T'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
